package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="pharmacy_management"
)
public class Admin  implements java.io.Serializable {


     private String name;
     private String password;
     private Set<Screens> screenses = new HashSet<Screens>(0);

    public Admin() {
    }

	
    public Admin(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public Admin(String name, String password, HashSet<Screens> screenses) {
       this.name = name;
       this.password = password;
       this.screenses = screenses;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="admin")
    public Set<Screens> getScreenses() {
        return this.screenses;
    }
    
    public void setScreenses(Set<Screens> screenses) {
        this.screenses = screenses;
    }




}


