package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BillCodeStore generated by hbm2java
 */
@Entity
@Table(name="bill_code_store"
    ,catalog="pharmacy_management"
)
public class BillCodeStore  implements java.io.Serializable {


     private int code;

    public BillCodeStore() {
    }

    public BillCodeStore(int code) {
       this.code = code;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }




}


