package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Drugs generated by hbm2java
 */
@Entity
@Table(name="drugs"
    ,catalog="pharmacy_management"
)
public class Drugs  implements java.io.Serializable {


     private String name;
     private String barcode;
     private String type;
     private int purchasingPrice;
     private int sellingPrice;
     private int discount;
     private int quantity;
     private int profit;
     private String company;

    public Drugs(String name, String company) {
        this.name = name;
        this.company = company;
    }

    public Drugs() {
    }

    public Drugs(String name, String barcode, String type, int purchasingPrice, int sellingPrice, int discount, int quantity, int profit, String company) {
       this.name = name;
       this.barcode = barcode;
       this.type = type;
       this.purchasingPrice = purchasingPrice;
       this.sellingPrice = sellingPrice;
       this.discount = discount;
       this.quantity = quantity;
       this.profit = profit;
       this.company = company;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Barcode", nullable=false, length=11)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="Type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="Purchasing_Price", nullable=false)
    public int getPurchasingPrice() {
        return this.purchasingPrice;
    }
    
    public void setPurchasingPrice(int purchasingPrice) {
        this.purchasingPrice = purchasingPrice;
    }

    
    @Column(name="Selling_price", nullable=false)
    public int getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(int sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    
    @Column(name="Discount", nullable=false)
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Profit", nullable=false)
    public int getProfit() {
        return this.profit;
    }
    
    public void setProfit(int profit) {
        this.profit = profit;
    }

    
    @Column(name="Company", nullable=false, length=100)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }




}


