package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LostDrugs generated by hbm2java
 */
@Entity
@Table(name="lost_drugs"
    ,catalog="pharmacy_management"
)
public class LostDrugs  implements java.io.Serializable {


     private String drugName;
     private String drugType;
     private int quantityDrug;

    public LostDrugs() {
    }

    public LostDrugs(String drugName, String drugType, int quantityDrug) {
       this.drugName = drugName;
       this.drugType = drugType;
       this.quantityDrug = quantityDrug;
    }
   
     @Id 

    
    @Column(name="Drug_Name", unique=true, nullable=false, length=100)
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    
    @Column(name="Drug_Type", nullable=false, length=100)
    public String getDrugType() {
        return this.drugType;
    }
    
    public void setDrugType(String drugType) {
        this.drugType = drugType;
    }

    
    @Column(name="Quantity_Drug", nullable=false)
    public int getQuantityDrug() {
        return this.quantityDrug;
    }
    
    public void setQuantityDrug(int quantityDrug) {
        this.quantityDrug = quantityDrug;
    }




}


