package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchasesBills generated by hbm2java
 */
@Entity
@Table(name="purchases_bills"
    ,catalog="pharmacy_management"
)
public class PurchasesBills  implements java.io.Serializable {


     private int billcode;
     private String barcode;
     private String name;
     private String type;
     private int purchasingPrice;
     private int sellingPrice;
     private int discount;
     private int quantity;
     private int total;
     private String company;
     private Date dateBill;

    public PurchasesBills() {
    }

    public PurchasesBills(int billcode, String barcode, String name, String type, int purchasingPrice, int sellingPrice, int discount, int quantity, int total, String company, Date dateBill) {
       this.billcode = billcode;
       this.barcode = barcode;
       this.name = name;
       this.type = type;
       this.purchasingPrice = purchasingPrice;
       this.sellingPrice = sellingPrice;
       this.discount = discount;
       this.quantity = quantity;
       this.total = total;
       this.company = company;
       this.dateBill = dateBill;
    }
   
     @Id 

    
    @Column(name="Billcode", unique=true, nullable=false)
    public int getBillcode() {
        return this.billcode;
    }
    
    public void setBillcode(int billcode) {
        this.billcode = billcode;
    }

    
    @Column(name="Barcode", nullable=false, length=100)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="Name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="Purchasing_Price", nullable=false)
    public int getPurchasingPrice() {
        return this.purchasingPrice;
    }
    
    public void setPurchasingPrice(int purchasingPrice) {
        this.purchasingPrice = purchasingPrice;
    }

    
    @Column(name="Selling_price", nullable=false)
    public int getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(int sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    
    @Column(name="Discount", nullable=false)
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="total", nullable=false)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

    
    @Column(name="Company", nullable=false, length=100)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DateBill", nullable=false, length=10)
    public Date getDateBill() {
        return this.dateBill;
    }
    
    public void setDateBill(Date dateBill) {
        this.dateBill = dateBill;
    }




}


