package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesBills generated by hbm2java
 */
@Entity
@Table(name="sales_bills"
    ,catalog="pharmacy_management"
)
public class SalesBills  implements java.io.Serializable {


     private int billCode;
     private Date billDate;
     private String drug1;
     private Integer unitPrice1;
     private Integer quantity1;
     private Integer total1;
     private Integer discount1;
     private Integer net1;
     private Integer profit1;
     private String drug2;
     private Integer unitPrice2;
     private Integer quantity2;
     private Integer total2;
     private Integer discount2;
     private Integer net2;
     private Integer profit2;
     private String drug3;
     private Integer unitPrice3;
     private Integer quantity3;
     private Integer total3;
     private Integer discount3;
     private Integer net3;
     private Integer profit3;
     private String drug4;
     private Integer unitPrice4;
     private Integer quantity4;
     private Integer total4;
     private Integer discount4;
     private Integer net4;
     private Integer profit4;
     private String drug5;
     private Integer unitPrice5;
     private Integer quantity5;
     private Integer total5;
     private Integer discount5;
     private Integer net5;
     private Integer profit5;
     private Integer totalnet;
     private Integer totalProfits;

    public SalesBills() {
    }

	
    public SalesBills(int billCode, Date billDate) {
        this.billCode = billCode;
        this.billDate = billDate;
    }
    public SalesBills(int billCode, Date billDate, String drug1, Integer unitPrice1, Integer quantity1, Integer total1, Integer discount1, Integer net1, Integer profit1, String drug2, Integer unitPrice2, Integer quantity2, Integer total2, Integer discount2, Integer net2, Integer profit2, String drug3, Integer unitPrice3, Integer quantity3, Integer total3, Integer discount3, Integer net3, Integer profit3, String drug4, Integer unitPrice4, Integer quantity4, Integer total4, Integer discount4, Integer net4, Integer profit4, String drug5, Integer unitPrice5, Integer quantity5, Integer total5, Integer discount5, Integer net5, Integer profit5, Integer totalnet, Integer totalProfits) {
       this.billCode = billCode;
       this.billDate = billDate;
       this.drug1 = drug1;
       this.unitPrice1 = unitPrice1;
       this.quantity1 = quantity1;
       this.total1 = total1;
       this.discount1 = discount1;
       this.net1 = net1;
       this.profit1 = profit1;
       this.drug2 = drug2;
       this.unitPrice2 = unitPrice2;
       this.quantity2 = quantity2;
       this.total2 = total2;
       this.discount2 = discount2;
       this.net2 = net2;
       this.profit2 = profit2;
       this.drug3 = drug3;
       this.unitPrice3 = unitPrice3;
       this.quantity3 = quantity3;
       this.total3 = total3;
       this.discount3 = discount3;
       this.net3 = net3;
       this.profit3 = profit3;
       this.drug4 = drug4;
       this.unitPrice4 = unitPrice4;
       this.quantity4 = quantity4;
       this.total4 = total4;
       this.discount4 = discount4;
       this.net4 = net4;
       this.profit4 = profit4;
       this.drug5 = drug5;
       this.unitPrice5 = unitPrice5;
       this.quantity5 = quantity5;
       this.total5 = total5;
       this.discount5 = discount5;
       this.net5 = net5;
       this.profit5 = profit5;
       this.totalnet = totalnet;
       this.totalProfits = totalProfits;
    }
   
     @Id 

    
    @Column(name="Bill_Code", unique=true, nullable=false)
    public int getBillCode() {
        return this.billCode;
    }
    
    public void setBillCode(int billCode) {
        this.billCode = billCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Bill_Date", nullable=false, length=10)
    public Date getBillDate() {
        return this.billDate;
    }
    
    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }

    
    @Column(name="Drug1", length=100)
    public String getDrug1() {
        return this.drug1;
    }
    
    public void setDrug1(String drug1) {
        this.drug1 = drug1;
    }

    
    @Column(name="unit_price1" )
    public Integer getUnitPrice1() {
        return this.unitPrice1;
    }
    
    public void setUnitPrice1(Integer unitPrice1) {
        this.unitPrice1 = unitPrice1;
    }

    
    @Column(name="Quantity1")
    public Integer getQuantity1() {
        return this.quantity1;
    }
    
    public void setQuantity1(Integer quantity1) {
        this.quantity1 = quantity1;
    }

    
    @Column(name="total1")
    public Integer getTotal1() {
        return this.total1;
    }
    
    public void setTotal1(Integer total1) {
        this.total1 = total1;
    }

    
    @Column(name="discount1")
    public Integer getDiscount1() {
        return this.discount1;
    }
    
    public void setDiscount1(Integer discount1) {
        this.discount1 = discount1;
    }

    
    @Column(name="net1")
    public Integer getNet1() {
        return this.net1;
    }
    
    public void setNet1(Integer net1) {
        this.net1 = net1;
    }

    
    @Column(name="profit1")
    public Integer getProfit1() {
        return this.profit1;
    }
    
    public void setProfit1(Integer profit1) {
        this.profit1 = profit1;
    }

    
    @Column(name="Drug2", length=100)
    public String getDrug2() {
        return this.drug2;
    }
    
    public void setDrug2(String drug2) {
        this.drug2 = drug2;
    }

    
    @Column(name="unit_price2")
    public Integer getUnitPrice2() {
        return this.unitPrice2;
    }
    
    public void setUnitPrice2(Integer unitPrice2) {
        this.unitPrice2 = unitPrice2;
    }

    
    @Column(name="Quantity2")
    public Integer getQuantity2() {
        return this.quantity2;
    }
    
    public void setQuantity2(Integer quantity2) {
        this.quantity2 = quantity2;
    }

    
    @Column(name="total2")
    public Integer getTotal2() {
        return this.total2;
    }
    
    public void setTotal2(Integer total2) {
        this.total2 = total2;
    }

    
    @Column(name="discount2")
    public Integer getDiscount2() {
        return this.discount2;
    }
    
    public void setDiscount2(Integer discount2) {
        this.discount2 = discount2;
    }

    
    @Column(name="net2")
    public Integer getNet2() {
        return this.net2;
    }
    
    public void setNet2(Integer net2) {
        this.net2 = net2;
    }

    
    @Column(name="profit2")
    public Integer getProfit2() {
        return this.profit2;
    }
    
    public void setProfit2(Integer profit2) {
        this.profit2 = profit2;
    }

    
    @Column(name="Drug3", length=100)
    public String getDrug3() {
        return this.drug3;
    }
    
    public void setDrug3(String drug3) {
        this.drug3 = drug3;
    }

    
    @Column(name="unit_price3")
    public Integer getUnitPrice3() {
        return this.unitPrice3;
    }
    
    public void setUnitPrice3(Integer unitPrice3) {
        this.unitPrice3 = unitPrice3;
    }

    
    @Column(name="Quantity3")
    public Integer getQuantity3() {
        return this.quantity3;
    }
    
    public void setQuantity3(Integer quantity3) {
        this.quantity3 = quantity3;
    }

    
    @Column(name="total3")
    public Integer getTotal3() {
        return this.total3;
    }
    
    public void setTotal3(Integer total3) {
        this.total3 = total3;
    }

    
    @Column(name="discount3")
    public Integer getDiscount3() {
        return this.discount3;
    }
    
    public void setDiscount3(Integer discount3) {
        this.discount3 = discount3;
    }

    
    @Column(name="net3")
    public Integer getNet3() {
        return this.net3;
    }
    
    public void setNet3(Integer net3) {
        this.net3 = net3;
    }

    
    @Column(name="profit3")
    public Integer getProfit3() {
        return this.profit3;
    }
    
    public void setProfit3(Integer profit3) {
        this.profit3 = profit3;
    }

    
    @Column(name="Drug4", length=100)
    public String getDrug4() {
        return this.drug4;
    }
    
    public void setDrug4(String drug4) {
        this.drug4 = drug4;
    }

    
    @Column(name="unit_price4")
    public Integer getUnitPrice4() {
        return this.unitPrice4;
    }
    
    public void setUnitPrice4(Integer unitPrice4) {
        this.unitPrice4 = unitPrice4;
    }

    
    @Column(name="Quantity4")
    public Integer getQuantity4() {
        return this.quantity4;
    }
    
    public void setQuantity4(Integer quantity4) {
        this.quantity4 = quantity4;
    }

    
    @Column(name="total4")
    public Integer getTotal4() {
        return this.total4;
    }
    
    public void setTotal4(Integer total4) {
        this.total4 = total4;
    }

    
    @Column(name="discount4")
    public Integer getDiscount4() {
        return this.discount4;
    }
    
    public void setDiscount4(Integer discount4) {
        this.discount4 = discount4;
    }

    
    @Column(name="net4")
    public Integer getNet4() {
        return this.net4;
    }
    
    public void setNet4(Integer net4) {
        this.net4 = net4;
    }

    
    @Column(name="profit4")
    public Integer getProfit4() {
        return this.profit4;
    }
    
    public void setProfit4(Integer profit4) {
        this.profit4 = profit4;
    }

    
    @Column(name="Drug5", length=100)
    public String getDrug5() {
        return this.drug5;
    }
    
    public void setDrug5(String drug5) {
        this.drug5 = drug5;
    }

    
    @Column(name="unit_price5")
    public Integer getUnitPrice5() {
        return this.unitPrice5;
    }
    
    public void setUnitPrice5(Integer unitPrice5) {
        this.unitPrice5 = unitPrice5;
    }

    
    @Column(name="Quantity5")
    public Integer getQuantity5() {
        return this.quantity5;
    }
    
    public void setQuantity5(Integer quantity5) {
        this.quantity5 = quantity5;
    }

    
    @Column(name="total5")
    public Integer getTotal5() {
        return this.total5;
    }
    
    public void setTotal5(Integer total5) {
        this.total5 = total5;
    }

    
    @Column(name="discount5")
    public Integer getDiscount5() {
        return this.discount5;
    }
    
    public void setDiscount5(Integer discount5) {
        this.discount5 = discount5;
    }

    
    @Column(name="net5")
    public Integer getNet5() {
        return this.net5;
    }
    
    public void setNet5(Integer net5) {
        this.net5 = net5;
    }

    
    @Column(name="profit5")
    public Integer getProfit5() {
        return this.profit5;
    }
    
    public void setProfit5(Integer profit5) {
        this.profit5 = profit5;
    }

    
    @Column(name="Totalnet")
    public Integer getTotalnet() {
        return this.totalnet;
    }
    
    public void setTotalnet(Integer totalnet) {
        this.totalnet = totalnet;
    }

    
    @Column(name="totalProfits")
    public Integer getTotalProfits() {
        return this.totalProfits;
    }
    
    public void setTotalProfits(Integer totalProfits) {
        this.totalProfits = totalProfits;
    }




}


