package com.store.dal.entities;
// Generated Jul 8, 2020 8:01:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Screens generated by hbm2java
 */
@Entity
@Table(name="screens"
    ,catalog="pharmacy_management"
)
public class Screens  implements java.io.Serializable {


     private int seq;
     private Admin admin;
     private String page;

    public Screens() {
    }

    public Screens(int seq, Admin admin, String page) {
       this.seq = seq;
       this.admin = admin;
       this.page = page;
    }
   
     @Id 

    
    @Column(name="seq", unique=true, nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Name", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="page", nullable=false, length=45)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }




}


